# Create like by post id
POST http://localhost:3000/api/posts/49afd4eb-ce03-426b-a436-c167f8185b22/likes?userId=123 HTTP/1.1
###

# Delete like by post id
DELETE http://localhost:3000/api/posts/49afd4eb-ce03-426b-a436-c167f8185b22/likes?userId=124 HTTP/1.1
###

# Get all likes by post
GET http://localhost:3000/api/posts/49afd4eb-ce03-426b-a436-c167f8185b22/likes HTTP/1.1
###
