-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "publish_date" DROP NOT NULL,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "announcement" DROP NOT NULL,
ALTER COLUMN "link" DROP NOT NULL,
ALTER COLUMN "post_text" DROP NOT NULL,
ALTER COLUMN "photo_url" DROP NOT NULL,
ALTER COLUMN "quote_text" DROP NOT NULL,
ALTER COLUMN "quote_author" DROP NOT NULL,
ALTER COLUMN "is_reposted" DROP NOT NULL,
ALTER COLUMN "video_link" DROP NOT NULL,
ALTER COLUMN "creator_user_id" DROP NOT NULL,
ALTER COLUMN "original_post_id" DROP NOT NULL;
